version: "3.0"
services:
  app-mqtt:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4445:4445
    volumes:
      - ../../../data/face_images:/data/face_images
      - ../../../data/human_images:/data/human_images
      - ../../../data/vehicle_images:/data/vehicle_images
  # kafka-face:
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile.worker
  #   ports:
  #     - 4446:4446

  # pgsql:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: qiKQc6mkJumfOaErq5g3sJgtXN17p0FD
  #     POSTGRES_USER: coreit
  #     POSTGRES_DB: isoc_backend
  #     PGDATA: '/var/lib/postgresql/data'
  #   volumes:
  #     - ./pg_data:/var/lib/postgresql/data
  #   ports:
  #     - 5435:5432
  
# volumes:
#   pg-data:
